version: '3'
services:
  nginx:
    image: nginx:1.15.0-alpine
    ports:
     - "80:80"
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf
     - /var/www/50x15/:/var/www/50x15/
     - /var/www/html/:/var/www/html/
    networks:
     - 50x15
     - wordpress

networks:
  50x15:
    external:
      name: 50x15_default
  wordpress:
    external:
      name: wordpress_default
